/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface InitOptions {
  /** Path to directory containing cef_screenshot_helper.exe + CEF runtime. */
  helperDir?: string
  /** Number of concurrent browser slots (default 3, max 10). Kept for backward compatibility — equivalent to browsers=1, tabs=N. */
  concurrency?: number
  /** Number of browser processes to spawn (default 1, max 5). Each process is an independent CEF instance with its own tabs. */
  browsers?: number
  /** Number of tabs (slots) per browser process (default 3, max 10). Total concurrency = browsers × tabs. */
  tabs?: number
}
export interface ScreenshotOptions {
  /** Viewport width in pixels (default 1920). */
  width?: number
  /** Viewport height in pixels (default 1080). */
  height?: number
  /** Extra delay in ms after page load before capture (default 500). */
  delay?: number
}
export declare function init(options?: InitOptions | undefined | null): Promise<void>
export declare function screenshot(url: string, options?: ScreenshotOptions | undefined | null): Promise<Buffer>
export declare function shutdown(): Promise<void>
