/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface InitOptions {
  /** Path to directory containing cef_screenshot_helper.exe + CEF runtime. */
  helperDir?: string
  /** Number of concurrent browser slots (default 3, max 10). */
  concurrency?: number
}
export interface ScreenshotOptions {
  /** Viewport width in pixels (default 1920). */
  width?: number
  /** Viewport height in pixels (default 1080). */
  height?: number
  /** Extra delay in ms after page load before capture (default 500). */
  delay?: number
}
export declare function init(options?: InitOptions | undefined | null): Promise<void>
export declare function screenshot(url: string, options?: ScreenshotOptions | undefined | null): Promise<Buffer>
export declare function shutdown(): Promise<void>
